import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Space_Grotesk({ subsets: ["latin"], weight: ["500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#151515]`}>
        <div className="max-w-[1440px] w-full m-auto">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
